-- Migration: v1.0.8__add_audit_columns_to_all_tables.sql
-- Description: Adds created_by, created_at, updated_by, updated_at audit columns to all database tables

ALTER TABLE app_settings
  ADD COLUMN created_by VARCHAR(100) DEFAULT NULL,
  ADD COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN updated_by VARCHAR(100) DEFAULT NULL;

ALTER TABLE attendance
  ADD COLUMN created_by VARCHAR(100) DEFAULT NULL,
  ADD COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN updated_by VARCHAR(100) DEFAULT NULL;

ALTER TABLE fee_heads
  ADD COLUMN created_by VARCHAR(100) DEFAULT NULL,
  ADD COLUMN updated_by VARCHAR(100) DEFAULT NULL,
  ADD COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE payments
  ADD COLUMN created_by VARCHAR(100) DEFAULT NULL,
  ADD COLUMN updated_by VARCHAR(100) DEFAULT NULL,
  ADD COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE payment_items
  ADD COLUMN created_by VARCHAR(100) DEFAULT NULL,
  ADD COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN updated_by VARCHAR(100) DEFAULT NULL,
  ADD COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE report_cards
  ADD COLUMN created_by VARCHAR(100) DEFAULT NULL,
  ADD COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN updated_by VARCHAR(100) DEFAULT NULL;

ALTER TABLE students
  ADD COLUMN created_by VARCHAR(100) DEFAULT NULL,
  ADD COLUMN updated_by VARCHAR(100) DEFAULT NULL;

ALTER TABLE student_fees
  ADD COLUMN created_by VARCHAR(100) DEFAULT NULL,
  ADD COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN updated_by VARCHAR(100) DEFAULT NULL;

ALTER TABLE student_sub_fees
  ADD COLUMN created_by VARCHAR(100) DEFAULT NULL,
  ADD COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN updated_by VARCHAR(100) DEFAULT NULL;

ALTER TABLE student_transport_monthly
  ADD COLUMN created_by VARCHAR(100) DEFAULT NULL,
  ADD COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN updated_by VARCHAR(100) DEFAULT NULL;

ALTER TABLE users
  ADD COLUMN created_by VARCHAR(100) DEFAULT NULL,
  ADD COLUMN updated_by VARCHAR(100) DEFAULT NULL,
  ADD COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
